### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by Mr-Lion** [martianyi/webpack-simple-serve#6]
Although the package is installed, the error that "webpack" was not found is displayed here.

Please fix it as soon as possible, otherwise I won't be able to use this here.

Thanks in advance.

![image](https://user-images.githubusercontent.com/6929357/144683898-9575f1c1-6e1a-43f6-bf5d-bfeb971cb9e7.png)

**Comment by martianyi** [comment]
webpack is declared as a peer dependence, you should run `npm i webpack -D` to install it by yourself.
